### ISSUE TITLE
Resolve .rsk addresses when sending

### ISSUE THREAD

**Issue by jessgusclark** [rsksmart/rwallet#108]
When sending tokens, accept an RNS domain as valid input. Resolve the domain to the address, if it exists, and then continue with the transaction.

Feature Request

![image](https://user-images.githubusercontent.com/766679/80701175-aba4bc80-8ae7-11ea-9c08-d8e062fdd935.png)

**Comment by chrisli30** [comment]
@jessgusclark that's the RNS feature we are working on. You come a bit early. We will let you know here once it's shipped. 😄

**Comment by imstar15** [comment]
commit 05e0eb57ed52a5a90ed8fb571878d70300e908c2
