### ISSUE TITLE
Push notification BTC amount needs to be formatted before displaying

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#112]
![image](https://user-images.githubusercontent.com/2616844/80925733-199aef00-8d47-11ea-9e07-34d0e9bdc297.png)

https://github.com/chrisli30/rwallet-server/pull/457/files

Besides, the sentence should be set in mobile, not backend code. The only thing backend sent should be JSON of the transaction data, such as
{
eventType, // tx, we only have one type of push notification for now
chain,
type,
symbol,
address,
from, // Used to determine body text
to, // Used to determine body text
amount,
status, //pending or confirmed
}

**Comment by imstar15** [comment]
This function is implemented by the backend.
