### ISSUE TITLE
[Wallet App Tester] Miner Fee spelt as Mineer Fee on Andriod

### ISSUE THREAD

**Issue by owans** [rsksmart/rwallet#117]
- In the send transaction, the **miner** fee below the Memo is spelt as **mineer** fee.

**Comment by chrisli30** [comment]
@owans thanks for reporting this. We've recognized and fixed that. It will show in the new release.

**Comment by owans** [comment]
Awesome

**Comment by chrisli30** [comment]
@imstar15 is this fixed? Can you attach the PR number and close it?

**Comment by imstar15** [comment]
Fixed. PR #71
