### ISSUE TITLE
Term and conditions not working 

### ISSUE THREAD

**Issue by dulcedu** [rsksmart/rwallet#14]
@chrisli30  Term and conditions not working 

Here some examples: 

- https://brd.com/terms
- https://wallet.coinbase.com/terms-of-service
- https://www.bitstamp.net/bitgo_customer_terms/ 

Educational: https://legacy.mycrypto.com/

**Comment by imstar15** [comment]
Can you open a browser page directly here, but there must be a back button to let the user come back
https://www.rsk.co/terms-conditions

@ zan768616253 Can you pop up a component from below, that is, a component that is obviously suspended above the current page
