### ISSUE TITLE
Error when trying to swap BTC to DOC

### ISSUE THREAD

**Issue by ManuFerrari** [rsksmart/rwallet#146]
Here is the error:

![image](https://user-images.githubusercontent.com/65308742/81852904-2206dd00-9532-11ea-9372-058f9941734d.png)

**Comment by chrisli30** [comment]
Hi @ManuFerrari looks like you are using an Android phone. We have made a backend service change, that your version number has to be v1.1.0 to work properly.

What's your Google Play account on your device? Let me add you to Google Play alpha tester list so you can download RSK Wallet from there.

**Comment by ManuFerrari** [comment]
Hi @chrisli30 , I am using an Iphone.

**Comment by chrisli30** [comment]
Got it. This is a coinswitch server responding issue. We have seen it a few times before. Contacting them to see if we can optimize this.

**Comment by ManuFerrari** [comment]
hi! I still have same issue.

**Comment by ManuFerrari** [comment]
seems I had an old version. really sorry. already updated and now it works
