### ISSUE TITLE
Incorrect name, Name contains invalid characters

### ISSUE THREAD

**Issue by jessgusclark** [rsksmart/rwallet#155]
I tried with uppercase and without, I'm on IOS.

Screenshots:
![image](https://user-images.githubusercontent.com/766679/82339167-6abd0b00-99f6-11ea-94af-2671860fdbac.png)

**Comment by chrisli30** [comment]
@imstar15

**Comment by imstar15** [comment]
Thanks for reporting Jesse!

**Comment by jessgusclark** [comment]
@imstar15 Happy to help! This issue wasn't just related to the space character. The first and last screen shot is only 'jesse' and "Jesse", no trailing space. I was unable to set any value for the name property.

**Comment by jessgusclark** [comment]
I tested this out today with the new release in testflight and it worked great!

**Comment by chrisli30** [comment]
@jessgusclark Awesome, thanks for testing!
