### ISSUE TITLE
Coinswitch: swap BTC for RBTC failed due to low BTC tx fee.

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#159]
Maxi:

I tried to swap btc for rbtc through the wallet yesterday, and the tx is still pending

I did it through coinswitch.co and it worked perfect

I think that the problem is a lower fee, who decide the fee in rsk wallet?

@imstar15 could you test if our BTC tx fee too low?

**Comment by imstar15** [comment]
User feedback:
Hi guys, something is happening with Coinswitch when users send BTC to receive RBTC or DOC
https://live.blockcypher.com/btc/tx/ce40a1f398ffcfd329192f8b5f88b4cc923744fb6969931745820a186a574ed9/
Another tx with problems:
https://live.blockcypher.com/btc/tx/2e84f10b20da71e23bac312be21fb4aa0176117c410100a04c6fe2a7bbebf7eb/

这里是两个交易：
交易1:
amount: 0.01961016 BTC
fee: 0.00008301 BTC
确认时间： 5 消失

交易2:
amount: 0.001115 BTC
fee: 0.00012696 BTC
确认时间： 超过6小时仍未被确认

![image](https://user-images.githubusercontent.com/16951509/82517664-2fceea80-9b50-11ea-9b60-0e0ba11d971b.png)
