### ISSUE TITLE
Question: why "Key" instead of "Wallet"?

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#162]
Hi,

I don't see why have the name Key, because it's confusing. Should be only Wallet and Assets. 

1- We add new Wallet but instead of Wallet name is added Key name.

![photo_2020-05-21_12-29-51](https://user-images.githubusercontent.com/1178856/82575851-606a5080-9b5f-11ea-96e9-bf502a345662.jpg)

2- Here you have "Key 1" but should be "Wallet 1" and the "8 Wallets" should be "8 Assets", no?

![photo_2020-05-21_12-30-13](https://user-images.githubusercontent.com/1178856/82576075-b808bc00-9b5f-11ea-95de-1dd7cf9803cd.jpg)

**Comment by chrisli30** [comment]
Yes this is true. We should all use "Wallet" instead of "Key". Marking this as enhancement.

**Comment by chrisli30** [comment]
@imstar15 I think we have addressed this issue in PR. If so please attach PR number here and  close.

**Comment by imstar15** [comment]
commit d58d00af7b254b3713b13ddb1afd95ce911f43fb
