### ISSUE TITLE
Should be Green color instead of Gray color

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#163]
See:

![photo_2020-05-21_15-35-07](https://user-images.githubusercontent.com/1178856/82593816-7127c000-9b79-11ea-9293-2f9338a3dfe4.jpg)

**Comment by chrisli30** [comment]
@AmazingBeerBelly can we change the color of phone top bar in the app?

**Comment by AmazingBeerBelly** [comment]
just black and white color
