### ISSUE TITLE
Received RBTC Notification does not show on Android

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#167]
Device: Google Pixel 4
Version: rWallet-V1.1.1-2020-05-21-release.apk

Does not receive confirmation of Receiving" and "Received", but saw transaction history.

TxHash:
https://explorer.testnet.rsk.co/tx/0xfdf00b52286d34cb6111d7978066a4c3728997ccecb2f4ba503a56994dceede2

Screenshot:
![image](https://user-images.githubusercontent.com/2616844/82619582-30d13d80-9b8b-11ea-8e28-d8666e9236bb.png)

**Comment by imstar15** [comment]
Kangbin update the code of product env,  and this issue is solved.
