### ISSUE TITLE
Sent Notification received twice for iOS device

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#168]
Device: iPhone X
Version: TestFlight v1.1.0

Saw two notification in a row(1 sec interval) for "Sent".

TxHash:
https://explorer.testnet.rsk.co/tx/0xfdf00b52286d34cb6111d7978066a4c3728997ccecb2f4ba503a56994dceede2

The From address is the wallet on my iPhone.

Screenshot: (I retried and got the same problem for RIF. The screenshot is from the 2nd tx)
![image](https://user-images.githubusercontent.com/2616844/82619878-f3b97b00-9b8b-11ea-9c49-2f4f14edaa1d.png)

**Comment by huhu2356** [comment]
i ask xing, the apk corresponding rwallet-server env is prod;
in previous, the prod code is not updated, so i updated;
may need to test again;

after updated, in theory, will not receive same notification mutiple times;
but sometimes may not get notification because of firebase;

**Comment by imstar15** [comment]
It's solved!
