### ISSUE TITLE
Rwallet crash when clicking on MIN button on exchange window and then click on Android back button

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#175]
Rwallet crash when clicking on MIN button on exchange window and then click on Android back button.

![photo_2020-05-22_10-47-39](https://user-images.githubusercontent.com/1178856/82675258-ed261480-9c1a-11ea-9961-06af46dbcc96.jpg)

**Comment by bitcoinuser** [comment]
If do not crash with Min button, try with Half or All button.

**Comment by chrisli30** [comment]
@imstar15  could you investigate?

**Comment by imstar15** [comment]
This problem does not repro. 
Which the version of app, device did you use?
@bitcoinuser

**Comment by bitcoinuser** [comment]
Hi,

I tested with the last version of Rwallet (the blue one) and with Xiaomi Mi8 Phone.

**Comment by imstar15** [comment]
I tested too with Xiaomi Mi8 and the last vesion.  
But This bug is not represent.
@bitcoinuser
