### ISSUE TITLE
In-app browser

### ISSUE THREAD

**Issue by alebanzas** [rsksmart/rwallet#176]

**Comment by ilanolkies** [comment]
I love Trust Wallet ux for this feature. It enables the whole defi experience in a simple way. 

![F2F0A0E1-4B10-4ACF-867A-FE8602C41EB6](https://user-images.githubusercontent.com/36084092/82699823-bfa19100-9c43-11ea-8024-85ea9a35253a.jpeg)

**Comment by imstar15** [comment]
commit e50ccb8a586091676029ea0570adf31f1f2978da
