### ISSUE TITLE
Ui scrollbar to be removed

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#177]
Hi, I think this scrollbar here should be removed, it looks strange. 

![0C400A08-48B9-4A59-91EF-6615F45A7852](https://user-images.githubusercontent.com/36084092/82699245-ab10c900-9c42-11ea-877b-62eeaffca255.jpeg)

**Comment by chrisli30** [comment]
Scroll bar should not be removed otherwise users won't know where the current position is. Instead, this bar should not overlap text in the list. It should be out on the right.

**Comment by imstar15** [comment]
@ilanolkies This problem have been solved in new version. You can update in TestFlight.
![image](https://user-images.githubusercontent.com/16951509/82778641-8c017980-9e84-11ea-9508-89285efaf9b5.png)

**Comment by ilanolkies** [comment]
Uh, I was outdated... sorry.
