### ISSUE TITLE
In-app faucet

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#178]
Nice feature: use faucet for testnet networks. Maybe it looks something like

![BC23057C-712E-4676-A685-E08B5E602AAC](https://user-images.githubusercontent.com/36084092/82699443-08a51580-9c43-11ea-9365-de5f4e0a0c1c.jpeg)

**Comment by chrisli30** [comment]
Yes, that would be interesting. We will need a proper UI element for that. Mark this as feature.

**Comment by chrisli30** [comment]
@imstar15 we need to add a line of text below "There is no transaction ...", saying "Get {symbol} from Testnet Faucet."  and link it to the faucet page.

We currently have RBTC and RIF faucet webpage. 
For RBTC we only need to fill in the wallet RBTC address.
For RIF, we will interact with the RIF website with web3.js or rsk3.js.

**Comment by ilanolkies** [comment]
I send you the RIF faucet contract. It allows to get 100 tRIF each day now. It can be executed either from the account owner or by a third parity. If it runs out of tokens, it can be filled back sending tRIF to the contract address.

https://github.com/riflabs/rif-faucet
https://github.com/riflabs/rif-faucet-client
https:/faucet.rifos.org

**Comment by chrisli30** [comment]
I like this feature. @imstar15 see if you can teach @AmazingBeerBelly on how to interact with the smart contract.

In our in-app browser, go to https://faucet.rifos.org/ and you should be able to interact with the website the same as MetaMask does in Chrome. Clicking on the Dispense button the website will give us the raw transaction to sign.

**Comment by imstar15** [comment]
commit e50ccb8a586091676029ea0570adf31f1f2978da
