### ISSUE TITLE
Button doesn't show correctly on portuguese language

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#190]
See:

![photo_2020-05-25_23-30-09](https://user-images.githubusercontent.com/1178856/82854840-fa275a00-9edf-11ea-9995-2579b298ec10.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser  good catch!

@imstar15 I feel like every button should have `overflow: hidden` style to make sure text doesn't over flow. Idea case is that we show them full, but it's better to have part of text hidden than overlow.
