### ISSUE TITLE
Option to exchange BTC lightning from external wallet to RBTC

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#198]
Hi,

I need to exchange a small amount of BTC to RBTC but it's very expensive because BTC onchain miner fee is high.
I was thinking if is possible to implement on Rif Wallet an option to exchange BTC Lightning from an external service to RBTC. For example: https://www.bitfinex.com/ allows deposit bitcoin lightning and has an option to trade BTC to RBTC too.
RIF Wallet provider could deposit BTC and RBTC 1 for 1 on bitfinex order book. So users of RIF Wallet will deposit Bitcoin lightning on the bitfinex account of Rif Wallet provider using bitfinex API and receive RBTC.

Is this possible?

**Comment by chrisli30** [comment]
@bitcoinuser We've considered your approach, however, we are compliant for users to deposit BTC to our Bitfinex account and do the exchange. Actually this approach is very hard for apps to be compliant.

We have another way of exchange BTC with RBTC coming up, which will always guarantee 1:1 ratio but takes longer.

**Comment by bitcoinuser** [comment]
> We have another way of exchange BTC with RBTC coming up, which will always guarantee 1:1 ratio but takes longer.

Yes, but I would like to exchange bitcoin lightning to RBTC.

**Comment by chrisli30** [comment]
> > We have another way of exchange BTC with RBTC coming up, which will always guarantee 1:1 ratio but takes longer.
> 
> Yes, but I would like to exchange bitcoin lightning to RBTC.

Understood. We will need to explore solution for that. I will update you here once we've got something.
