### ISSUE TITLE
Support bitcoin lightning by using acinq service

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#210]
Hi,

I think Rwallet great and I really would like to see bitcoin lightning support on it. Recently I was following a chat conversation on Phoenix wallet telegram group where someone asked if was possible to use Acinq service to integrate lightning on his own app. 
I think the Rwallet focus is on RSK and this is great. But I think you should support things people that don't know Rsk would like to use too. This is great because people may like Rwallet UI/UX design, use lightning, exchange bitcoin between DOC, RBTC in a easy way, all with the same seed. 

Obs. You could support lightning without much efforts

Look the chats:

![Captura de tela de 2020-06-07 20-36-53](https://user-images.githubusercontent.com/1178856/83983151-6e132a80-a902-11ea-8949-684c88a8195b.png)

![Captura de tela de 2020-06-07 20-37-03](https://user-images.githubusercontent.com/1178856/83983155-75d2cf00-a902-11ea-9e85-2f720c67b968.png)

**Comment by chrisli30** [comment]
@bitcoinuser we need to do due diligence on this service first. It needs to be proven.
