### ISSUE TITLE
Keyboard should show only numbers and no letters

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#216]
Keyboard should show only numbers and no letters.

![photo_2020-06-16_10-09-39](https://user-images.githubusercontent.com/1178856/84778723-c9f04a00-afb9-11ea-8e7f-a0e55cdfdd0c.jpg)

**Comment by chrisli30** [comment]
Yeah, this is right 👍 

There's no point display a letter keyboard for this input.

@AmazingBeerBelly we need to change this keyboard to Numbers only.

**Comment by AmazingBeerBelly** [comment]
commit d46ae9377ba124733ef86c2bc3626f3dcaa621cf

**Comment by AmazingBeerBelly** [comment]
commit d46ae9377ba124733ef86c2bc3626f3dcaa621cf

**Comment by AmazingBeerBelly** [comment]
commit d46ae9377ba124733ef86c2bc3626f3dcaa621cf
