### ISSUE TITLE
If wallet list is empty, should show a notification when user select the wallet to open the dapp.

### ISSUE THREAD

**Issue by AmazingBeerBelly** [rsksmart/rwallet#219]
When the user clicks DAPP to select a wallet, if the wallet list is empty at this time, a notification needs to pop up to prompt the user to create a wallet

**Comment by chrisli30** [comment]
![DB_no_wallet](https://user-images.githubusercontent.com/2616844/85098833-9fb4ad00-b1b0-11ea-8ef8-7d5e13b29a45.png)

Uploaded to Lanhu.

Title: No Wallet Available
Body: There is no wallet available for this Dapp yet. Please navigate to Wallet Creation page to either create or import a wallet first.

Button: Create or Import
Button2: Cancel

**Comment by AmazingBeerBelly** [comment]
commit 4d673f2a6baa1f18a5da9b2bc16ca3b3aa300870
