### ISSUE TITLE
The app shouldn't show the bottom tab bar during the first time open.

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#221]
![Screenshot_2020-06-20-19-08-24-472_com rsk rwallet reactnative](https://user-images.githubusercontent.com/2616844/85213269-df92a600-b310-11ea-9398-de15d0d06515.jpg)

The user needs to set up a wallet the first time he opens the app

**Comment by imstar15** [comment]
The old version of the UI logic is also the same, currently not modified
