### ISSUE TITLE
Styles of popup model don't match that of design

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#222]
1. The title color, the font of body look different from the sketch design.
1. The body text are stretched horizontally.
1. The space between "Cancel" and the bottom border is smaller than the design. Cancel is too close to the bottom border.

Need to double check the styles.

![Screenshot_2020-06-20-19-14-51-804_com rsk rwallet reactnative](https://user-images.githubusercontent.com/2616844/85213301-647dbf80-b311-11ea-9f45-d6c3c8c13c31.jpg)

**Comment by AmazingBeerBelly** [comment]
commit 4d673f2a6baa1f18a5da9b2bc16ca3b3aa300870
