### ISSUE TITLE
Dapp Browser page is different from the design

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#223]
1. There is no blue "Dapp" on top.
1. There is no "Powered by RSK" at bottom.
1. Font color, weight of Dapp title, description and url are all different from the design.

Please check the latest design on Lanhu. The implementation needs to match the design!

![Screenshot_2020-06-20-19-19-09-591_com rsk rwallet reactnative](https://user-images.githubusercontent.com/2616844/85213336-f08fe700-b311-11ea-9813-14a27ae28daa.jpg)

**Comment by AmazingBeerBelly** [comment]
commit ad16583fbf57c0a75576b0063c7f862d459eb064
