### ISSUE TITLE
RNS response error doesn't give a clear reason

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#227]
1. The page is still pending for another 3 secs after error notification shows up. If we decide to show notification page while user stays on this page, the feedback should be simultaneously.
![image](https://user-images.githubusercontent.com/2616844/85213701-c0971280-b316-11ea-9077-6decc136817b.png)

2. The error doesn't show a clear reason why the registration failed. I think it might be due to the name entered is already registered, but I can't tell from the message.

Oh, no that's mainnet address which is not enabled yet. Hmm, we need to explain the reason better here.
![image](https://user-images.githubusercontent.com/2616844/85213706-cab91100-b316-11ea-8629-a66f26fbbb55.png)

3. Then I retried to register with the same name "chris.wallet.rsk" on testnet. It seems to take too long to give me the error response. Besides, the response should be "That nickname is not available" if we know it has been registered.

![image](https://user-images.githubusercontent.com/2616844/85213902-3f8d4a80-b319-11ea-9742-4bb48238b6cf.png)

4. Then I left this page, re-enter and typed "chris.wallet.rsk" again. The page then can give me the "nickname unavailable" popup. So the problem in No.3 was, that if I register "chris.wallet.rsk" two times in a row, the second time the app doesn't notify me about the nick unavailability.
![image](https://user-images.githubusercontent.com/2616844/85213941-d65a0700-b319-11ea-8707-c15f159c0839.png)

**Comment by imstar15** [comment]
Problem 2 does not need to be repaired at present
I can'tl let problem 3,4 reappear
