### ISSUE TITLE
Open Me->Developer Portal in build-in web browser

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#231]
Can we open the Developer Portal in our build-in web browser? It is the only one using external link right now so we need to change it to build-in to be consistent with "Term of Use".

Make sure there's major issues showing the site in build-in web browser.

**Comment by imstar15** [comment]
我觉得不是很有必要，因为外部浏览器的功能比我们内部浏览器多，比如书签，收藏之类的，体验也要好些。那些社交网络链接在我们内部浏览器打开不一定是好的选择哦
