### ISSUE TITLE
Dapps bottom tab logo and title problem

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#232]
1. DApp的logo不清晰，是因为没有图？
1. 另外为什么底部的几个按钮的样子跟设计上感觉不一样，我感觉字比设计上的大了，看起来笨重，这里要按照设计再修改
![image](https://user-images.githubusercontent.com/2616844/85214279-9137d400-b31d-11ea-8886-98aca4f0cc1f.png)

**Comment by AmazingBeerBelly** [comment]
commit b253562c4aa421282a71b120ced141d34e0700b2
