### ISSUE TITLE
feat:  Remind users to upgrade

### ISSUE THREAD

**Issue by imstar15** [rsksmart/rwallet#242]
**Is your feature request related to a problem? Please describe.**
The app should pop up an interface to remind the user to upgrade when it starts.

**Describe the solution you'd like**
Send the current client version number to the server to get the latest version, and let the application pop up an interface to remind the user to upgrade.
There are two cases: recommended upgrade and forced upgrade.

**Describe alternatives you've considered**
Same as above

**Additional context**
Nothing

**Comment by chrisli30** [comment]
Example,
![image](https://user-images.githubusercontent.com/2616844/90206909-c569c700-dd99-11ea-8a71-d30c61fae123.png)

**Comment by chrisli30** [comment]
We need to fetch the version and update strategy from server

getServerInfo

serverVersion: (just for reference)
latestClientVersion: (the version app should be on)
upgradeOptions: {
title:
body:
appStoreUrl:
googlePlayUrl:
isOptional: false or true (if false use have to click on Update and go to App Store)
}

@tinyyxx @imstar15
