### ISSUE TITLE
firebase.messaging().getToken() will block app launching

### ISSUE THREAD

**Issue by imstar15** [rsksmart/rwallet#248]
**Describe the bug** (required)
网络不畅时（包括未翻墙），firebase.messaging().getToken() 会把整个APP卡住。
不知道是不是某些国产机器才会出现这个情况。

**App & Device** (required)
 - Wallet App version: v1.2.0
 - Device: HUAWEI nova youth
 - OS version: EMUI 5.1, Android 7.0
 
**To Reproduce**
1. Install APP
2. Launch

**Screenshots** (required for high priority)
![image](https://user-images.githubusercontent.com/16951509/86015379-12951200-ba54-11ea-9c52-26841f4a7b7d.png)

**Expected behavior**
App launch smothly

**Comment by chrisli30** [comment]
嗯，这个得搞清楚是哪一段代码卡了主流程。

**Comment by imstar15** [comment]
rwallet/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java

```
String token = FirebaseInstanceId
        .getInstance()
        .getToken(senderId, FirebaseMessaging.INSTANCE_ID_SCOPE);
```

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId

public String getToken (String senderId, String scope)
Returns a token that authorizes a sender ID to perform an action on behalf of the application identified by Instance ID.

This generates an Instance ID if it does not exist yet, which starts periodically sending information to the Firebase backend (see getId()).

This is similar to an OAuth2 token except, it applies to the application instance instead of a user.

This is a blocking function so do not call it on the main thread.

**Comment by imstar15** [comment]
据读react-native-firebase得到信息，它使用了googleFirebaseInstanceId.getInstance().getToken，它是一个阻塞函数，不应在主线程进行调用。

不能在主线程调用这个函数的话，如何在android另外的线程，得学习下。
