### ISSUE TITLE
Suggestion: change black color of bottom bar

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#266]
Hi,

I think the bottom bar with color black is not good. I think black color should be used when Rif Wallet implement Dark mode.

My suggestion is to change to something like this:

![Imagem 1](https://user-images.githubusercontent.com/1178856/86538045-df2a0b80-bec9-11ea-8522-878b4613601d.jpg)

**Comment by chrisli30** [comment]
> Hi,
> 
> I think the bottom bar with color black is not good. I think black color should be used when Rif Wallet implement Dark mode.
> 
> My suggestion is to change to something like this:
> 
> ![Imagem 1](https://user-images.githubusercontent.com/1178856/86538045-df2a0b80-bec9-11ea-8522-878b4613601d.jpg)

Hi @bitcoinuser ,

Sorry I didn't get your point. You meant something like what? The bar in your screenshot is still black.

**Comment by bitcoinuser** [comment]
Hi @chrisli30 the background on my example is not black.

**Comment by bitcoinuser** [comment]
On Rif Wallet is black:

![Imagem 2](https://user-images.githubusercontent.com/1178856/86543461-1cf05980-bef5-11ea-9474-215f07ffb344.jpg)

**Comment by chrisli30** [comment]
Mark as won't fix.
