### ISSUE TITLE
No RNS nickname popup after wallet creation.

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#285]
**Describe the bug** (required)
After "Create a Wallet", no popup is shown on the first tab, wallet dashboard.

**App & Device** (required)
 - Wallet App version: 1.2.0
 - Device: Samsung galaxy s9 plus
 - OS version: 

**Screenshots** (required for high priority)
![image](https://user-images.githubusercontent.com/2616844/87202153-d021cf80-c2b4-11ea-8c55-0952e694a1c6.png)

**Additional context**
The language settings is Spanish.

**Comment by imstar15** [comment]
![image](https://user-images.githubusercontent.com/16951509/87273403-9991c200-c50b-11ea-8d24-f55cd72b826d.png)

I repeated the operation, but the bug was not reproduced

**Comment by chrisli30** [comment]
Closed as not-repro
