### ISSUE TITLE
Terms & Conditions - Overlap Menus

### ISSUE THREAD

**Issue by filipe-iovlabs** [rsksmart/rwallet#300]
**Describe the bug** (required)
When you are in T&C and open for example the "The Stack" or "Develop" options, the next screens have an internal menu. So opening again the Hamburger menu will result on a clash of both menus and Ui issues

**App & Device** (required)
 - Wallet App version: 1.2.0
 - Device: iPhone 11 Max
 - OS version: iOS 13.6
 
**To Reproduce**
1. Open App
2. Click on 'Read Terms and conditions'
3. Open hamburger menu and click 'The Stack'
4. Open hamburger menu and see the UI issues

**Comment by chrisli30** [comment]
@imstar15  please take a look at this issue to see if it's our app's

**Comment by imstar15** [comment]
@chrisli30  It's a issue of rsk web

![image](https://user-images.githubusercontent.com/16951509/89243408-7653c180-d636-11ea-9265-1137de83640b.png)

**Comment by chrisli30** [comment]
@alebanzas Do you know who's responsible for this page? The mobile view of the terms page needs to be fixed.

**Comment by chrisli30** [comment]
Closing this issue due to unrelated to RWallet.
