### ISSUE TITLE
Terms & Conditions - Default Language

### ISSUE THREAD

**Issue by filipe-iovlabs** [rsksmart/rwallet#301]
**Describe the bug** (required)
I open the language and it identifies my language, in my case Portuguese, but after I click and open the Terms & Conditions option, the default language of the text is in English. Meaning I need to go to the menu and select my language.

**App & Device** (required)
 - Wallet App version: 1.2.0
 - Device: iPhone 11 Max
 - OS version: iOS 13.6
 
**To Reproduce**
1. Open App, and see if it open in a language different from English as the default of mobile options
2. Click on 'Read Terms and conditions'
3. See the initial text is English

**Comment by chrisli30** [comment]
We need 3 more languages: Japanese, Russian and Korean.
