### ISSUE TITLE
RBTC Send throws "need more balance to transfer"

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#319]
**Describe the bug** (required)
RBTC Send throws "need more balance to transfer"

**App & Device** (required)
 - Wallet App version: 1.2.0 (14)
 - Device: iPhone

**Screenshots** (required for high priority)
![image](https://user-images.githubusercontent.com/2616844/88836774-1a97bd00-d18c-11ea-8541-9275ebeccabe.png)

**Additional context**
https://explorer.rsk.co/address/0x2c4a4a346ddc3122c2628dbe9dbbca1bbd59551c

**Comment by imstar15** [comment]
fixed #320
