### ISSUE TITLE
tRIF Faucet transaction is not shown in history

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#325]
testnet address
0x5665a8C841a049B559D98AA006d3ECaec2e4aB19

![image](https://user-images.githubusercontent.com/2616844/88991154-b6145500-d294-11ea-994a-ac5b501ef7d9.png)

**Comment by bgorlick** [comment]
I see the same

**Comment by chrisli30** [comment]
@bgorlick  this one is tricky. We need to hard code transaction recognition from faucet contract to identify the incoming tx. Mark as Won't fix.
