### ISSUE TITLE
Always appear the message (Network Error - Your device can not connect to the server)

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#332]
Always appear the message (Network Error - Your device can not connect to the server)

Android: 10

![photo_2020-08-01_16-32-06](https://user-images.githubusercontent.com/1178856/89109101-a28ff800-d414-11ea-954c-149227d95926.jpg)

![photo_2020-08-01_16-33-04](https://user-images.githubusercontent.com/1178856/89109113-b4719b00-d414-11ea-8243-d2c586b7956c.jpg)

**Comment by bitcoinuser** [comment]
This problem happens if I update Rwallet. I solved the problem erasing app data on Android config and creating a new wallet.

**Comment by chrisli30** [comment]
Cool, yes new version is required because we changed logic of user session
