### ISSUE TITLE
We have Portuguese Brazilian language but we are missing BRL currency

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#333]
We have Portuguese Brazilian language but we are missing BRL currency

![photo_2020-08-01_19-17-32](https://user-images.githubusercontent.com/1178856/89111409-d1fe2f00-d42b-11ea-9196-683ad9d5d54a.jpg)

**Comment by chrisli30** [comment]
No plan to add more currency yet

**Comment by bitcoinuser** [comment]
O que acha @solangegueiros?
