### ISSUE TITLE
Send All not translated on app but on strings is translated on Portuguese Brazilian file

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#336]
Send All not translated on app but on strings is translated on Portuguese Brazilian file.

![photo_2020-08-02_11-20-27](https://user-images.githubusercontent.com/1178856/89125094-5f846200-d4b2-11ea-809c-1b8cb3c94fcf.jpg)

**Comment by chrisli30** [comment]
@imstar15 Could you take a look at this issue?
