### ISSUE TITLE
MOC Dapp not rendered correctly

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#337]
See the difference (look the country flag on top right) on Dapp browser and Brave Browser

![photo_2020-08-02_11-32-45](https://user-images.githubusercontent.com/1178856/89125359-3c5ab200-d4b4-11ea-9c8b-1a260e3c14bf.jpg)

![photo_2020-08-02_11-33-41](https://user-images.githubusercontent.com/1178856/89125365-441a5680-d4b4-11ea-9a5a-0615cc00cf95.jpg)

**Comment by chrisli30** [comment]
@AmazingBeerBelly Let's double check if our dapps "RIF on Chain" url is rif.moneyonchain.com and Money on Chain url is alpha.moneyonchain.com

**Comment by AmazingBeerBelly** [comment]
Checked, "RIF on Chain" is "https://rif.moneyonchain.com/" and "Money on Chain" is "https://alpha.moneyonchain.com/".

**Comment by bitcoinuser** [comment]
Why closed? I don't think you understood the issue I reported.

Look the country flag.

**Comment by bitcoinuser** [comment]
Doesn't show the EN when browsing the dapp using Rwallet. But on Brave show it.
