### ISSUE TITLE
I don't think make sense translate some dapps information on dapps window 

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#338]
Hi,

I see that the translations of MOC Dapp (Dinheiro na Cadeia) to Portuguese doesn't make sense. I don't know if is an automatic translation but I think it should be kept as English in this case.

![photo_2020-08-02_16-07-57](https://user-images.githubusercontent.com/1178856/89130346-93737d80-d4da-11ea-9200-93264e11fac5.jpg)

**Comment by bitcoinuser** [comment]
cc @solangegueiros

**Comment by chrisli30** [comment]
Then we need to fix the translation. I think they need to be translated

**Comment by bitcoinuser** [comment]
> Then we need to fix the translation. I think they need to be translated

At least the project names shouldn't be translated. Only the project description.

**Comment by chrisli30** [comment]
> At least the project names shouldn't be translated. Only the project description.

That I agree. Could you help translate Pt-Br?

Thanks!

**Comment by chrisli30** [comment]
@AmazingBeerBelly 忠伟，"rif on chain" doesn't need to be translated. Let's keep title of all Dapps as original, in English.

**Comment by AmazingBeerBelly** [comment]
Fixed on parse-dashboard.
