### ISSUE TITLE
Bug: If I click cancel button on Android fingerprint window, I only can access with PIN

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#341]
Hi, If I click on cancel on Android fingerprint "window", then appear the rwallet fingerprint popup. If I tap the fingerprint "drawing" on popup, appear the Android fingerprint "window" again. But after these steps the fingerprint doesn't work. So I need to cancel and insert the PIN or restart the app.
Obs. Android 10

![photo_2020-08-03_10-12-37](https://user-images.githubusercontent.com/1178856/89186900-d7b25c80-d572-11ea-968b-cb9868a77634.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser 
Could you fill in the information of
1. What device are you using?
2. What Android version specifically are you using?

We need those two info to repro this issue.

**Comment by bitcoinuser** [comment]
![photo_2020-08-03_17-59-48](https://user-images.githubusercontent.com/1178856/89226930-2c75c780-d5b3-11ea-831f-74f8882b9cc0.jpg)
