### ISSUE TITLE
(Not enough balance....) not translated to Portuguese Brazilian and not on strings file.

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#342]
(Not enough balance....) not translated to Portuguese Brazilian and not on strings file.

![photo_2020-08-03_10-21-14](https://user-images.githubusercontent.com/1178856/89187283-7474fa00-d573-11ea-8860-65133f6175e5.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser This issue is address. Please try to download the latest app from Google Android.
https://play.google.com/apps/internaltest/4700153005107669205

**Comment by bitcoinuser** [comment]
I think will be fixed when https://github.com/rsksmart/rwallet/pull/345 be merged.
