### ISSUE TITLE
(My 1st Wallet) not translated to Portuguese Brazilian and not on strings file

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#343]
(My 1st Wallet) not translated to Portuguese Brazilian and not on strings file

**Comment by chrisli30** [comment]
@imstar15 can you take a look at this issue?

**Comment by chrisli30** [comment]
@bitcoinuser do you know how to translate that string "1st" to Portuguese Brazilian (not hard-code way)?

**Comment by bitcoinuser** [comment]
> @bitcoinuser do you know how to translate that string "1st" to Portuguese Brazilian (not hard-code way)?

The translation will be (Minha 1ª Carteira). But this translation to Portuguese is strange. I think in english should be a simple thing like (Wallet 1) and in portuguese (Carteira 1)

**Comment by bitcoinuser** [comment]
> @bitcoinuser do you know how to translate that string "1st" to Portuguese Brazilian (not hard-code way)?

No hard-code way you mean like this: Minha Primeira Carteira. 

Long phrase and strange.

**Comment by chrisli30** [comment]
@imstar15 did we address this issue?

**Comment by bitcoinuser** [comment]
Please reopen. This was not fixed.
