### ISSUE TITLE
Why on Dapps appear an option to choose wallet if I have only one wallet on Rwallet?

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#346]
Why on Dapps appear an option to choose wallet if I have only one wallet on Rwallet?

![photo_2020-08-03_11-18-21](https://user-images.githubusercontent.com/1178856/89192831-7c389c80-d57b-11ea-96f4-485f4e01220c.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser this is confirm with you the address and balance in the wallet. We will keep that.
