### ISSUE TITLE
Dapps window showing strange things

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#352]
See:

![photo_2020-08-04_10-35-59](https://user-images.githubusercontent.com/1178856/89300551-c59df000-d63e-11ea-908e-03038e5d9595.jpg)

**Comment by chrisli30** [comment]
hmm weird, @AmazingBeerBelly Could you check why is that?

Thanks @bitcoinuser .

**Comment by chrisli30** [comment]
Let's add HTTP/HTTPS URL check to this list. 

1. Do not display invalid URL.
1. Display a RSK logo as default.
