### ISSUE TITLE
Problem on rif testnet faucet

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#353]
![photo_2020-08-04_11-09-04](https://user-images.githubusercontent.com/1178856/89303711-ed8f5280-d642-11ea-97d5-dd35371a8f2b.jpg)

**Comment by chrisli30** [comment]
@AmazingBeerBelly we need to take a look at this error. Check to see if it is because wallet selected is wrong (such as tRIF/tRBTC not enabled)
