### ISSUE TITLE
Make the qrcode icon bigger

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#355]
Hi,

Sometimes I try to click on Qrcode icon and I need to try more than one time because it's very small. If you could make this icon a little bigger will be great.

![photo_2020-08-04_12-04-20](https://user-images.githubusercontent.com/1178856/89310487-292e1a80-d64b-11ea-8ea8-4ed07d588217.jpg)

**Comment by chrisli30** [comment]
@imstar15 yeah let's enlarge the touchable area of that icon
