### ISSUE TITLE
Android back button doesn't close popup

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#356]
I think Android back button should close the popup here:

![photo_2020-08-04_12-15-50](https://user-images.githubusercontent.com/1178856/89311451-6515af80-d64c-11ea-9907-14cfcf8b4f7a.jpg)

**Comment by bitcoinuser** [comment]
In my opinion, the cancel button should be removed and a X close button should be added too.

![photo_2020-08-04_15-02-25](https://user-images.githubusercontent.com/1178856/89328527-e88ecb00-d663-11ea-8c4d-65a96d780c57.jpg)

**Comment by chrisli30** [comment]
Nah, it's not a website. X on top left will be hard to click.

**Comment by chrisli30** [comment]
> I think Android back button should close the popup here:
> 
> ![photo_2020-08-04_12-15-50](https://user-images.githubusercontent.com/1178856/89311451-6515af80-d64c-11ea-9907-14cfcf8b4f7a.jpg)

@imstar15 can you check if this cancel button works?
