### ISSUE TITLE
Moneyonchain not rendered correctly on rwallet dapp browser

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#357]
Rwallet dapp browser:

![photo_2020-08-04_14-15-24](https://user-images.githubusercontent.com/1178856/89324318-7ca96400-d65d-11ea-9692-71ddd9722329.jpg)

Brave browser:

![photo_2020-08-04_14-15-30](https://user-images.githubusercontent.com/1178856/89324348-86cb6280-d65d-11ea-842a-db8befe5e61a.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser we don't control the web of MoC. This issue we need to forward to MoC repo.

**Comment by bitcoinuser** [comment]
I tested now and it was fixed. Thanks.
