### ISSUE TITLE
I think the stop button is not necessary

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#359]
There are three buttons very near each one. I think stop button is not necessary.

![photo_2020-08-04_15-21-14](https://user-images.githubusercontent.com/1178856/89330540-cd718a80-d666-11ea-96c9-e4b6317b188f.jpg)

**Comment by chrisli30** [comment]
It's not a Stop button

The left most button should be Go Back (to previous page)
The X button is to close the browser.

@imstar15  could you make sure the 2 buttons working correct?

**Comment by bitcoinuser** [comment]
Yes, I was wrong about stop button. But the back button at least on moneyonchain, always take me back to rwallet dapps window.
And I think the buttons are very close to the others.

**Comment by chrisli30** [comment]
> Yes, I was wrong about stop button. But the back button at least on moneyonchain, always take me back to rwallet dapps window.
> And I think the buttons are very close to the others.

Yes, I agree. The browser header is currently a little cluttered and will be re-designed.

**Comment by bitcoinuser** [comment]
Back button works.
