### ISSUE TITLE
Should be (add this Asset) and not (these Assets)

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#360]
As it's only possible to add one custom asset at time, doesn't make sense (these Assets). Should be (this Asset)

![photo_2020-08-04_17-13-35](https://user-images.githubusercontent.com/1178856/89340482-33194300-d676-11ea-8ec7-d1609ffbec6a.jpg)

**Comment by chrisli30** [comment]
That's right. Thanks @bitcoinuser 

@imstar15 let's change the working to "this asset", instead of "These Assets"
