### ISSUE TITLE
In Dapp Browser, if no asset is available the app should allow user to turn on that asset

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#362]
When I click on dapp that the asset is not enabled on my wallet, show a popup to create or import a wallet. But I think should ask me to enable the Asset, no?

![photo_2020-08-04_17-38-45](https://user-images.githubusercontent.com/1178856/89342829-ba1bea80-d679-11ea-998f-6d18a5cc5285.jpg)

**Comment by chrisli30** [comment]
It's a good suggestion. I've added the request to "Enhancement".

**Comment by bitcoinuser** [comment]
Hi @chrisli30 and @imstar15  I see that the problem here is that if I enable tRIF asset and I don't enable tRBTC, when I go to tRIF faucet, show to create or import a wallet. The problem is solved if I enable tRBTC too.
So I think the solution is: If I enable tRIF asset, should automatically enable tRBTC asset too.

**Comment by chrisli30** [comment]
Related to #426
