### ISSUE TITLE
In the 2FA section, Google Pixel 5 should show "Biometric" instead of "Fingerprint"

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#363]
**Describe the bug** (required)
In the 2FA section, Google Pixel 5 should show "Biometric" instead of "Fingerprint"

Pixel 4 and 5 have face recognition function. We need to support it.

**App & Device** (required)
 - Wallet App version: 1.2.1
 - Device: Google Pixel 5
 
**Screenshots** (required for high priority)
![image](https://user-images.githubusercontent.com/2616844/89356008-99e82d80-d671-11ea-81b7-3e936bb70539.png)

**Comment by imstar15** [comment]
https://github.com/hieuvp/react-native-fingerprint-scanner

The latest version of this library supports face unlocking, but currently I don’t have a corresponding phone (google pixel 4) for testing.
