### ISSUE TITLE
Cancel segwit/legacy modal

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#378]
I cant go back whn I need to choose segwit or legacy. I would like to be able to cancel BTC wallet.

![Image from iOS](https://user-images.githubusercontent.com/36084092/89549103-45ae8c00-d7de-11ea-867d-e8ec6dd8dcf4.png)

**App & Device** (required)
 - Wallet App version: TestFlight latest
 - Device: iPhone XR
 - OS version: iOS latest

**Comment by chrisli30** [comment]
This popup shows when user already confirmed their selection of assets, and clicked on the CREATE button. At this step user cant go back even without this popup. We don't allow user to go back here because it will be over-complicated
