### ISSUE TITLE
Deselecting all currencies

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#379]
I want to deselect all selected coins and choose one when creating wallet. IMHO the CREATE button should be locked and not the last asset chosen. Now I have to choose first and deselect the not wanted after selecting a new one. I would like to be able to

1. Deselect all mainnet coins selected by default
2. Select one or many for testnet

![Image from iOS (1)](https://user-images.githubusercontent.com/36084092/89549466-b81f6c00-d7de-11ea-8744-9ebc4608659c.png)

**App & Device** (required)
 - Wallet App version: TestFlight latest
 - Device: [iPhone XR
 - OS version: iOS latest

**Comment by chrisli30** [comment]
This is a good suggestion. 

Thanks @ilanolkies

**Comment by chrisli30** [comment]
@imstar15  let's address this issue.
