### ISSUE TITLE
PIN creation requires PIN three times

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#380]
When creating the app you can choose a PIN and the confirm it. Why after confirming the pin I’m asked the pin again? I did 3 steps

1. Choose pin
2. Confirm pin
3. Unlock with pin

IMHO 3. is not necessary

**App & Device** (required)
 - Wallet App version: TestFlight latest
 - Device: [iPhone XR
 - OS version: iOS latest

**Comment by chrisli30** [comment]
I think it's the same as you create a password (which require input twice for confirmation) during sign-up, and then sign in to a web app.

@imstar15 please evaluate how much code we need to change to remove the first Passcode pop up right after wallet creation.
