### ISSUE TITLE
RNS Wording

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#382]
The app uses a lot of terms to define a same thing - an RNS domain:

- Name - in wallet screen
- Domain - in app first launch modal
- Nickname - in domain paring confirmation

I would recommend to use only ONE term to define what an RNS domain is for the rWallet, don't matter what term is but yes to keep it all around the app. Using different terms can confuse the users.

**App & Device** (required)
 - Wallet App version: TestFlight latest
 - Device: [iPhone XR
 - OS version: iOS latest

**Comment by chrisli30** [comment]
That's a good catch. Using different terms confuses user. I would go for **Nickname** for regular user to understand.

@imstar15 let's get this addressed.
