### ISSUE TITLE
Incoming notification is translated on Portuguese Brazilian file but not on Rwallet.

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#388]
![photo_2020-08-07_17-53-17](https://user-images.githubusercontent.com/1178856/89687685-09128b80-d8d7-11ea-970f-e2808f774a94.jpg)

**Comment by chrisli30** [comment]
@imstar15 
We need to address this. Those text needs to be translated.

**Comment by bitcoinuser** [comment]
Here another example:

![photo_2020-08-12_18-06-28](https://user-images.githubusercontent.com/1178856/90068166-98001900-dcc6-11ea-85ea-b2a4a9517c32.jpg)

**Comment by imstar15** [comment]
Fixed.
Notification text is sent by backend, so we fixed it in backend.
