### ISSUE TITLE
Bitpro token doesn`t show the price in dollar

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#389]
![photo_2020-08-07_18-01-13](https://user-images.githubusercontent.com/1178856/89688158-ff3d5800-d8d7-11ea-8db1-19c9116a4069.jpg)

**Comment by chrisli30** [comment]
Custom asset doesn't have price shown yet.

**Comment by bitcoinuser** [comment]
I see this is fixed now.
