### ISSUE TITLE
Exchanging and Receiving words translated on Brazilian Portuguese file but not on Rwallet

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#390]
![photo_2020-08-07_18-17-50](https://user-images.githubusercontent.com/1178856/89689223-53493c00-d8da-11ea-987c-c2ea303aca84.jpg)

**Comment by bitcoinuser** [comment]
Hum, I don`t see exchanging word on English translation file.

**Comment by chrisli30** [comment]
@imstar15  please check
