### ISSUE TITLE
Date format is wrong on Portuguese Brazilian

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#393]
The date format that appear on rwallet is Ago 7º 2020 but should be 7 Ago 2020

![photo_2020-08-08_19-50-47](https://user-images.githubusercontent.com/1178856/89721153-79411000-d9b0-11ea-82e8-0f55d8ea3564.jpg)

**Comment by chrisli30** [comment]
@imstar15 check whether the format is made by moment.format();

Use jsFiddle to make sure moment created the format for pt-br.
http://jsfiddle.net/brandonscript/rLjQx/

**Comment by imstar15** [comment]
@bitcoinuser @chrisli30 
```
const moment = require('moment');

moment.locale('pt-br');
const now = moment().format('MMM Do YYYY HH:mm:ss A ZZ');
console.log('now: ', now);
```
output: 
`now:  Ago 10º 2020 21:08:17 PM +0800
`

**Comment by bitcoinuser** [comment]
> @bitcoinuser @chrisli30
> 
> ```
> const moment = require('moment');
> 
> moment.locale('pt-br');
> const now = moment().format('MMM Do YYYY HH:mm:ss A ZZ');
> console.log('now: ', now);
> ```
> 
> output:
> `now: Ago 10º 2020 21:08:17 PM +0800 `

The correct format is 10 Ago 2020

**Comment by chrisli30** [comment]
Okay thanks @imstar15, @bitcoinuser the moment.format("lll")

gives us **11 de Agosto de 2020 às 10:26**

Is that Okay?

**Comment by bitcoinuser** [comment]
> Okay thanks @imstar15, @bitcoinuser the moment.format("LLL")
> 
> gives us **11 de Agosto de 2020 às 10:26**
> 
> Is that Okay?

Yes, It ok.
