### ISSUE TITLE
Strange: My father Android Rwallet app was updated yesterday and crash when open. My Rwallet on my phone didn't update to the new version.

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#399]
Strange: My father Android Rwallet app was updated yesterday and crash when open. My Rwallet on my phone didn't update to the new version.

**Comment by chrisli30** [comment]
@bitcoinuser 

What are the OS of your father's and yours?

**Comment by bitcoinuser** [comment]
All the two devices are Android

**Comment by bitcoinuser** [comment]
Updated
