### ISSUE TITLE
Crash when opening Rwallet 1.2.2 

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#400]
![Screenshot_2020-08-10-06-08-02-956_com miui bugreport](https://user-images.githubusercontent.com/1178856/89767511-73425080-dad0-11ea-864e-0c6249bdacd7.jpg)

**Comment by bitcoinuser** [comment]
Hi @chrisli30, could you please release a new Rwallet version as soon as possible to fix this? I'm unable to open Rwallet. Always crash. Thanks.

**Comment by chrisli30** [comment]
@bitcoinuser We just tested the download on 3 different phones. No problem.

You need to follow our issue template to give your device info and repro steps.

Did you download this version from Google Play?

**Comment by bitcoinuser** [comment]
Yes, I downloaded from Google play. I know 3 people with the same problem.

**Comment by bitcoinuser** [comment]
![Screenshot_2020-08-10-23-35-30-277_com android vending](https://user-images.githubusercontent.com/1178856/89851166-3888f880-db62-11ea-97de-59c551339c5a.jpg)

**Comment by bitcoinuser** [comment]
![Screenshot_2020-08-10-23-37-14-005_com android settings](https://user-images.githubusercontent.com/1178856/89851255-71c16880-db62-11ea-8666-808e0feaffb7.jpg)

**Comment by bitcoinuser** [comment]
@chrisli30 Looks like it's crashing on Xiaomi phones.

**Comment by rodolfhoalves** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/36309850/89851620-4ab76680-db63-11ea-8a0b-152aabb055a3.png)

**Comment by bitcoinuser** [comment]
Or maybe the crash is related to updating with Portuguese Brazilian language set on rwallet.

**Comment by chrisli30** [comment]
@bitcoinuser I think XiaoMi's system language settings is "ptbr" instead of "pt-br". Pixel 4 has "pt-br".

I think the fix would be that if we see "ptbr" we hard-code convert it to pt-br.

What do you think?

**Comment by bitcoinuser** [comment]
> @bitcoinuser I think XiaoMi's system language settings is "ptbr" instead of "pt-br". Pixel 4 has "pt-br".
> 
> I think the fix would be that if we see "ptbr" we hard-code convert it to pt-br.
> 
> What do you think?

I'm not a developer, so I don't know how to fix it.
