### ISSUE TITLE
Date format is wrong to Brazilian Portuguese

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#414]
Appear (Ago 7 2020( but should be something like (7 de Agosto 2020)

![photo_2020-08-12_10-10-11](https://user-images.githubusercontent.com/1178856/90019085-50589d80-dc84-11ea-84bc-43fb90718e63.jpg)

**Comment by chrisli30** [comment]
@imstar15  Let's use standard formatting for all dates in Brazilian Portuguese

**Comment by imstar15** [comment]
moment.format(‘LL’)
Output:
7 de Agosto de 2020
