### ISSUE TITLE
On add assets, if I enable tRIF, should automatically enable tRBTC too

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#425]
On add assets, if I enable tRIF, should automatically enable tRBTC too.

If i go to Dapps page and click on tRif faucet with only tRIF asset enabled, doesn't work (show no wallet available popup). Needs to enable tRBTC too to work.

**Comment by chrisli30** [comment]
I think we should notify user in tRif Faucet that this app requires tRBTC, instead of turn on the asset for them.

**Comment by chrisli30** [comment]
I've created a #426 for this issue.
