### ISSUE TITLE
The notification strings on Portuguese Brazilian needs to be improved but they are not on translation file.

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#434]
Hi,

I need to improve this translation but I can't find where to change it:

![photo_2020-08-26_10-17-46](https://user-images.githubusercontent.com/1178856/91308397-9da93480-e785-11ea-9b80-d23d134033c3.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser It has to be configured on server side. What's the value you want to use? We will change it for you.

**Comment by bitcoinuser** [comment]
> @bitcoinuser It has to be configured on server side. What's the value you want to use? We will change it for you.

In this case I will use (O recebimento de 0.00064 RBTC foi confirmado).

Please paste here all other server side strings so I can verify and translate appropriately. Thanks.

**Comment by chrisli30** [comment]
@imstar15 Can you copy paste all server-side Brazilian Portuguese localization here?

**Comment by imstar15** [comment]
**en**

```
{
  "notification": {
    "rnsSuccess": {
      "title": "Succeeded to link RNS nickname",
      "body": "You wallet address is linked to {{subdomain}}."
    },
    "rnsFailed": {
      "title": "Failed to link RNS nickname",
      "body": "You wallet address is not linked to {{subdomain}}."
    },
    "sentTx": {
      "title": "{{symbolLetter}} Sent",
      "body": "Your outgoing transaction of {{amount}} {{symbolLetter}} is confirmed."
    },
    "receivedTx": {
      "title": "{{symbolLetter}} Received",
      "body": "Your incoming transaction of {{amount}} {{symbolLetter}} is confirmed."
    },
    "receivingTx": {
      "title": "{{symbolLetter}} Receiving",
      "body": "You have an incoming transaction of {{amount}} {{symbolLetter}} pending."
    },
    "updateInfo": {
      "title": "App Update Required",
      "body": "Dear user,\nA new version of RWallet is available. Please update the app and re-open.\nThank you."
    }
  }
}

```

**pt-BR**

```
{
  "notification": {
    "rnsSuccess": {
      "title": "Foi possível vincular o apelido RNS",
      "body": "O endereço da sua carteira está vinculado ao {{subdomain}}."
    },
    "rnsFailed": {
      "title": "Falha ao vincular o apelido RNS",
      "body": "O endereço da carteira não está vinculado ao {{subdomain}}."
    },
    "sentTx": {
      "title": "{{symbolLetter}} enviado",
      "body": "Sua transação de saída de {{amount}} {{symbolLetter}} é confirmada."
    },
    "receivedTx": {
      "title": "{{symbolLetter}} Recebido",
      "body": "Sua transação de entrada de {{amount}} {{symbolLetter}} é confirmada."
    },
    "receivingTx": {
      "title": "Recebendo {{symbolLetter}}",
      "body": "Você tem uma transação de entrada de {{amount}} {{symbolLetter}} pendentes."
    },
    "updateInfo": {
      "title": "Atualização do aplicativo necessária",
      "body": "Querido usuário,\nUma nova versão do RWallet está disponível. Atualize o aplicativo e abra novamente.\nObrigado."
    }
  }
}

```

**Comment by bitcoinuser** [comment]
Hi, here is all strings updated. Please use it for Brazilian Portuguese Language. Thanks.


{
  "notification": {
    "rnsSuccess": {
      "title": "Apelido RNS vinculado com sucesso",
      "body": "O endereço da sua carteira está vinculado a {{subdomain}}."
    },
    "rnsFailed": {
      "title": "Falha ao vincular o apelido RNS",
      "body": "O endereço da carteira não está vinculado a {{subdomain}}."
    },
    "sentTx": {
      "title": "{{symbolLetter}} Enviado",
      "body": "O envio da transação no valor de {{amount}} {{symbolLetter}} foi confirmado."
    },
    "receivedTx": {
      "title": "{{symbolLetter}} Recebido",
      "body": "A transação recebida no valor de {{amount}} {{symbolLetter}} foi confirmada."
    },
    "receivingTx": {
      "title": "Recebendo {{symbolLetter}}",
      "body": "Você recebeu uma transação pendente de confirmação no valor de {{amount}} {{symbolLetter}}."
    },
    "updateInfo": {
      "title": "Atualização do aplicativo necessária",
      "body": "Olá usuário,\nUma nova versão da RWallet está disponível. Atualize o aplicativo e abra novamente.\nObrigado."
    }
  }
}

**Comment by bitcoinuser** [comment]
> > @bitcoinuser It has to be configured on server side. What's the value you want to use? We will change it for you.
> 
> In this case I will use (O recebimento de 0.00064 RBTC foi confirmado).
> 
> Please paste here all other server side strings so I can verify and translate appropriately. Thanks.

Ignore this one.

**Comment by bitcoinuser** [comment]
@chrisli30 Any news here? strings was updated?

**Comment by chrisli30** [comment]
@imstar15 could you coordinate with backend dev to update the strings on server side?

**Comment by imstar15** [comment]
@chrisli30 
Yes. It's updated and need review.

**Comment by imstar15** [comment]
Fixed by backend
