### ISSUE TITLE
Strange value when using approve DoC transaction on pool https://app.rskswap.com/

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#436]
See:

obs. should be 10 Doc

![photo_2020-08-26_19-15-40](https://user-images.githubusercontent.com/1178856/91362371-bb4fbb80-e7d0-11ea-92a0-46b2dbbb64a0.jpg)

**Comment by bitcoinuser** [comment]
![photo_2020-08-26_20-27-38](https://user-images.githubusercontent.com/1178856/91366613-9f511780-e7da-11ea-8713-d745f2325ac6.jpg)

**Comment by imstar15** [comment]
https://explorer.rsk.co/tx/0x669044a18feb2f0144da3d96231de2ac5737505971c08ecc8f9b3a4eb06191e7?__ctab=Logs

The value of this transaction is 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

**Comment by bitcoinuser** [comment]
> https://explorer.rsk.co/tx/0x669044a18feb2f0144da3d96231de2ac5737505971c08ecc8f9b3a4eb06191e7?__ctab=Logs
> 
> The value of this transaction is 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

But the transaction removed 10 doc from me. Shouldn't show this info?

**Comment by bitcoinuser** [comment]
Look here: https://blockscout.com/rsk/mainnet/tx/0xbf9b5d549d699e6855777e6fb7f988fe1b80f77cc5452beb39b99db6a314d526/token_transfers

**Comment by imstar15** [comment]
It's fixed by back-end.

**Comment by bitcoinuser** [comment]
Looks like it's fixed but now do not show the past transactions:

![photo_2020-09-30_13-47-49](https://user-images.githubusercontent.com/1178856/94715247-97c5e680-0323-11eb-84c4-052e7965aeb1.jpg)
