### ISSUE TITLE
Wrbtc can't be added on Rwallet custom assets

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#440]
I don't have wrbtc token on Rwallet, so I tried to add wrbtc (Contract: 0x967f8799aF07DF1534d48A95a5C9FEBE92c53ae0) but show this message:

![photo_2020-08-27_12-29-24](https://user-images.githubusercontent.com/1178856/91463021-437da180-e861-11ea-8a2b-ddc13c46ac9a.jpg)

**Comment by imstar15** [comment]
Database have same symbol, WRBTC, address: 0x1945d8aEdc005C900C796E31cce040363A6658d2

**Comment by chrisli30** [comment]
@bitcoinuser Do you know the official smart contract address of WRBTC? We have seen two addresses.
