### ISSUE TITLE
Looks like Rwallet request info from explorer.rsk.co but this has problems

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#450]
Looks like Rwallet request info from explorer.rsk.co but this has problems.

At this moment looks like explorer.rsk.co it's not updating information at this time. So I did a transaction on rskswap.com using the same seed used on Rwallet. The information of the transaction was not updated on Rwallet interface.

I think Rwallet should:

1- Use more than one service to request this data. 
2- Rwallet show information on interface that the service is offline.

**Comment by bitcoinuser** [comment]
Strange: looks like explorer.rsk.co is updating correctly now but my Rwallet do not update the transactions.

**Comment by chrisli30** [comment]
> I think Rwallet should:

You are right. The data source is the same from explorer.rsk.co.

No, we will not add a secondary data source. The backend of explorer.rsk.co should work 99.99% of time.
