### ISSUE TITLE
Can't use android back button. Only option is close Rwallet or create the wallet

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#453]
I can't go back using android back button when I'm on this popup. The only option is create the wallet or close Rwallet.

![photo_2020-09-01_11-43-54](https://user-images.githubusercontent.com/1178856/91866177-9a5fee00-ec48-11ea-8767-718b207270d2.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser yes, at this step you have verified the 12-word and 90% done in creating a wallet. All you need to do is to select one of the two Bitcoin wallet formats. Why would you want to go back?

**Comment by bitcoinuser** [comment]
> @bitcoinuser yes, at this step you have verified the 12-word and 90% done in creating a wallet. All you need to do is to select one of the two Bitcoin wallet formats. Why would you want to go back?

No @chrisli30. I didn't have verified the 12-word at this step. I just clicked create wallet and create button.

**Comment by bitcoinuser** [comment]
Still think it's wontfix? If yes, I will close the bug. Thanks.

**Comment by chrisli30** [comment]
@bitcoinuser let us confirm the case. I'll close it if still won't fix.

**Comment by chrisli30** [comment]
@bitcoinuser , yep this is not necessary. Won't fix. It's Okay to close now.
