### ISSUE TITLE
On read only wallet, assets disabled still appear on main window.

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#478]
Version of Rwallet. 1.3.0

Problem: I added a read only wallet using my rns nickname, so Rwallet added automatically the assets RIFP and RDOC but I don't have funds on these assets.
So after I added the wallet, I tried to disable these assets but when I go back to main window the assets are still there.

**Comment by chrisli30** [comment]
@imstar15 We should hide those two assets if user disable them.
