### ISSUE TITLE
Backup on read only wallets should show a different message

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#479]
Backup on read only wallets should show a different message

Now I see this:

![photo_2020-09-15_21-32-19](https://user-images.githubusercontent.com/1178856/93278436-0db24580-f79b-11ea-91e3-598688f661d3.jpg)

**Comment by chrisli30** [comment]
@imstar15 Readonly Wallet shouldn't have this Backup option. We need to remove it.
