### ISSUE TITLE
Adding custom token is not working with tokens that has the same symbol

### ISSUE THREAD

**Issue by jonathansmirnoff** [rsksmart/rwallet#481]
**Describe the bug** (required)
If two or more tokens has the same symbol is not possible to none of them to add to the wallet. Using the option Add Custom Asset.

**App & Device** (required)
 all
 
**To Reproduce**
1. Go to Add Asset
2. Click on '+ Custom'
3. Put the address '0x86aa2f176e068254a8CFA9F4791c3f51644A1f11'
4. Select Mainnet option false.
5. See error "Internal server error: Please contact customer support"
(Also I sow another error in that past similar to: "there is already token in the network with the same name"

**Comment by chrisli30** [comment]
Hi @jonathansmirnoff , what version of the app are you using?

**Comment by jonathansmirnoff** [comment]
1.2.3

**Comment by chrisli30** [comment]
The error should be "there is already token in the network with the same name". We are releasing a new version 1.3.0 and once installed you will be able to see that error.

We will address this issue. Previously, the app disallow user to add a token that has the same name as one which has be registered already.

**Comment by jonathansmirnoff** [comment]
@chrisli30 the idea is that app in the future allows you to add tokens that have the same name, right?
In my case I have created a token for testing and I added it to de wallet. Then I had to create another token with the same name, but I couldn't use any token because of the logic that have described.
