### ISSUE TITLE
ERC20 Notifications

### ISSUE THREAD

**Issue by jonathansmirnoff** [rsksmart/rwallet#482]
When an erc20 transaction notification is received, it would be great if it is possible to decode it and show the amount of token that was transferred. Currently, it only show rbtc value. In the case of and erc20 transfer, the value of rbtc is 0. This is confusing to users.

**Comment by chrisli30** [comment]
@jonathansmirnoff what token are you referring to? 

Is there any way to know that an address is a ERC20 contract, without having its ABI?

**Comment by jonathansmirnoff** [comment]
I thinking of any token. It would be great to know the amount of RIF that you are receiving. 
I don't know if there is any easy way to do it. Maybe using the tokens endpoint in the explorer api.

**Comment by chrisli30** [comment]
> I thinking of any token. It would be great to know the amount of RIF that you are receiving.

We checked our logic. As long as the smart contract has ERC20 standard transfer function the app will show the transfer amount.
