### ISSUE TITLE
Click on notification should open Funds Sent but show Transaction list

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#504]
RWallet version: 1.3.1 on Android

1- I have the same seed on Nifty and RWallet. 
2- So I sent a transaction using Nifty and received a notification on Android that the transaction sent was confirmed. 
3- So I clicked on the notification.

Result:

When clicking on notification, open the transactions list 

Expected result:

Should open:

![photo_2020-09-29_12-49-27](https://user-images.githubusercontent.com/1178856/94582096-400b7a80-0252-11eb-820b-b493fb2105d2.jpg)

**Comment by chrisli30** [comment]
hmm yeah, navigating to this page makes more sense.

@imstar15 I don't remember why we direct to transaction list page instead of transaction detail page. Could you coordinate with Zhongwei to update the navigation logic?
