### ISSUE TITLE
Show Read-only label for wallets in Settings

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#509]
RWallet 1.3.1 on Android

1- On Wallets on Me, should show a string that the wallet is read only wallet.

![photo_2020-10-01_10-27-54](https://user-images.githubusercontent.com/1178856/94815350-ce0d6f80-03d0-11eb-883e-1fb16ca8e204.jpg)

2- When deleting a Read only wallet should popup a different message, like: Are you sure you want to delete this read only wallet? now appear this:

![photo_2020-10-01_10-29-15](https://user-images.githubusercontent.com/1178856/94815500-f8f7c380-03d0-11eb-8e4d-df830800860a.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser good suggestions!

1. The read-only wallets should have a label before "1 Asset"
2. The text during deletion would be "Are you sure you want to delete this Read-only wallet?"
Also, regular wallet text should be update to "Are you sure you want to delete this wallet?"
