### ISSUE TITLE
Strange data when sharing asset address 

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#512]
RWallet 1.3.1 on Android

Steps to reproduce:

1 Go to receive BTC and click on share button and choose for example Telegram IM messenger app.

Expected result: See only the address pasted on telegram chat

What I see:

bc1qjzurazxz7nkt7ur3lmcwcprzcj6zkavwwuzqve file:///data/user/0/com.rsk.rwallet.reactnative/cache/ReactNative-snapshot-image2977945269891054681.jpg

**Comment by chrisli30** [comment]
@imstar15 Can you take a look at this issue? It seems that we copied unwanted data out to telegram
