### ISSUE TITLE
Suggestion: only show names on bottom bar when the button be clicked

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#514]
To allow more buttons on bottom bar, I think on bottom bar, the names should only appear when clicked. Like this:

![Bottom](https://user-images.githubusercontent.com/1178856/94941631-8b6c9580-04ab-11eb-94d8-5631d175ccc0.jpg)

**Comment by chrisli30** [comment]
No, it's unclear to users not to show text of the bottom tabs. This is a won't fix.
