### ISSUE TITLE
Minimum sat/byte on fee slider should be 1

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#516]
RWallet 1.3.1 on Android

I tried to send a bitcoin transaction using RWallet but I didn't like that I couldn't specify sat/byte. The minimum fee that RWallet gave me as an option to choose was higher than I would like to choose.

**Comment by bitcoinuser** [comment]
I know RWallet has something like this: https://twitter.com/MayankDotCh/status/1312728525447720961

But the minimum on RWallert is not 1 sat/byte as it should be.

**Comment by bitcoinuser** [comment]
On Umbrel the minimum sat/byte is 1, see: https://twitter.com/MayankDotCh/status/1312977825016676352

**Comment by chrisli30** [comment]
@bitcoinuser We have made decision for this topic. The low tier gas fee already has the tendency to take a very long time, let alone 1 sat/byte. The wallet is here to solve a sending problem for the majority and transactions needs to go through at a high rate. If you are power user and want super low transaction cost you probably already know to choose other tools. Apple doesn't allow users to customize many things either. They have three versions for each generation.

**Comment by bitcoinuser** [comment]
Hi @chrisli30 I disagree because we already have custom option on RWallet. If the option is to be simple, the custom option should be removed. I think it's should be simple to implement something on slider that give an estimation of when the transaction will be confirmed, something like this: https://twitter.com/coinyfees/status/1313463358725582849
I really would like to use RWallet to store bitcoins too because of multisig option that you are implementing. I wouldn't like to use another wallet because I can't specify a low fee on RWallet. So I really hope you reconsider this. Thanks.

**Comment by chrisli30** [comment]
Okay, that makes sense. Yeah since we have the custom slider we can do that, but I hope everyone is not using 1 sat/byte ...

Remove won't fix label.
