### ISSUE TITLE
bug: clearly distinguish between network ID and coin type

### ISSUE THREAD

**Issue by bguiz** [rsksmart/rwallet#523]
**Describe the bug** (required)

- Code appears to refer to coin type as network ID
  - [`src/common/wallet/cointype.js`](https://github.com/rsksmart/rwallet/blob/feaf13d/src/common/wallet/cointype.js#L16) defines
    - RBTC's `networkId` as `137` and
    -tRBTC's `networkId` as `37310`.
  - These are indeed correct values for their coin types, but are incorrect values for their network IDs
    - RBTC is on RSK Mainnet, and RSK Mainnet's network ID is `30` (not `137`)
    - tRBTC's is on RSK Testnet, and RSK Testnet's network ID is `31` (not `37310`)
- This may result in incorrect assumptions elsewhere within the code base
  - For example, the `networkId` values are being [used in derivation paths](https://github.com/rsksmart/rwallet/blob/feaf13d/src/common/wallet/rbtccoin.js#L62), and used in [key pair generation from seed phrase](https://github.com/rsksmart/rwallet/blob/feaf13d/src/common/wallet/rbtccoin.js#L112)
  - This is probably working right now because of a double negative effect where the mistakes in `cointype.js` are masked by the inverse of the same mistake in the `rbtccoin.js`
  - However, if `networkId` is actually used as a network ID elsewhere within the code base, we will get wrong results.

**App & Device** (required)

Not applicable
 
**To Reproduce**

Not applicable

**Screenshots** (required for high priority)

Not applicable

**Expected behavior**

- Alter `cointype.js` to specify both `networkId` and `coinType`
- Scrub through entire code base for usage of `networkId`, and verify in each case whether it was intended as a network ID or a coin type, and change as appropriate.
- Unrelated to this bug report, but also observed, due to lexical adjacency:
  - `cointype.js` does not appear to distinguish between the protocol level cryptocurrencies (e.g. `RBTC` on `RSK`) and the application level cryptocurrencies such as tokens (e.g. `RIF` on `RSK`).
  - It would make sense to define that attribute within `cointype.js`. Otherwise, is this currently defined elsewhere?

**Additional context**

- Reference: [Account Based RSK Addresses](https://developers.rsk.co/rsk/architecture/account-based/)
  - Details on RSK's derivation path, checksum, and chain ID.
  - Note that the derivation path section defines the coin types.
  - Note that chain ID is equivalent to network ID.

**Comment by chrisli30** [comment]
@bguiz This bug is related to #519  which is being worked on and in review. Please take a look at it : )

**Comment by chrisli30** [comment]
Nice, this if very detailed oriented!

**Comment by bguiz** [comment]
Addendum: `networkId` and `chainId` are indeed **not** interchanegable, however most dev tools (Ganache/ Truffle/ etc) implement `networkId` that refers to `chainId`, so I think this is OK. Just noting that here in case we circle back around to this. [PR #519](https://github.com/rsksmart/rwallet/pull/519/files) thus adequately addresses this requirement now.

So closing this issue now.

I think it would be best to address the below issue in a **separate PR** so let's merge PR #519.

----

Note that the PR does not address the following unrelated but adjacent issue:

```markdown
- Unrelated to this bug report, but also observed, due to lexical adjacency:
  - `cointype.js` does not appear to distinguish between the protocol level cryptocurrencies (e.g. `RBTC` on `RSK`) and the application level cryptocurrencies such as tokens (e.g. `RIF` on `RSK`).
  - It would make sense to define that attribute within `cointype.js`. Otherwise, is this currently defined elsewhere?
```

To address this separate issue, I think the best approach would be to observe how other tools define a list of coins and follow the structure/ format of that, then refactor as necessary. I think Nifty would be a good place to start regarding this - not MetaMask as it does not handle derivation paths of non-Ethereum blockchain networks properly.

**Comment by chrisli30** [comment]
The ERC20 smart contract address is acting as the identifier to a token such as RIF right now. Smart contract of all tokens are saved in the app storage. RBTC doesn't have that address value since it's not needed.
