### ISSUE TITLE
ethers library function is duplicate of rsk3.js

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#544]
From Brendan,

while I was digging around, I also found that we're importing both rsk3.js and ethers.js.
both of these libraries provide the same functionality, so I'm not sure why this is needed.
https://github.com/rsksmart/rwallet/blob/f6338d61744ab1c35a5e0284dd8258e7bce35f60/src/pages/dapp/browser.js#L11-L12
and this has had an impact on the code base already having fragmented implementations.
see
https://github.com/rsksmart/rwallet/blob/f6338d61744ab1c35a5e0284dd8258e7bce35f60/src/pages/dapp/browser.js
const signWallet = new ethers.Wallet(privateKey, this.provider);
and
https://github.com/rsksmart/rwallet/blob/f6338d61744ab1c35a5e0284dd8258e7bce35f60/src/common/transaction/rbtccoin.js#L109-L114
await rsk3.accounts.privateKeyToAccount(privateKey);
in which wallets are generated using different libraries

**Comment by bgorlick** [comment]
ACK, removing the ethers library with the same functionality makes sense.
