### ISSUE TITLE
Sending to Domain on RNS address does not work (yourdomain.rsk)

### ISSUE THREAD

**Issue by openartstudio** [rsksmart/rwallet#546]
Hello!
I try to send some rBTC to addres on domain RNS like yourdomain.rsk and I got error: "addres is not valid"

I use rWallet 1.3.0 on Android 

 
![Error with RNS domain](https://files.gitter.im/5d839779d73408ce4fcb7e42/VH5S/image.png)

Please help me.

**Comment by tinyyxx** [comment]
@openartstudio Hi, you should type `openart.wallet.rsk`. This is your full domain.

**Comment by openartstudio** [comment]
yes but i'm talking about something else
I have olso another domain - my own: "openart.rsk" 
When I try to send to openart.rsk I have error.
Try to send me some rBTC on my address "openart.rsk"...

**Comment by tinyyxx** [comment]
@openartstudio Sorry, let me check it out.

**Comment by openartstudio** [comment]
ok. waiting for information :-)
