### ISSUE TITLE
Didn't find strings to translate Mainnet and Testnet 

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#554]
RWallet 1.3.1 on Android

Didn't find strings to translate Mainnet and Testnet in this case:

![photo_2020-10-17_11-41-50](https://user-images.githubusercontent.com/1178856/96339892-c48d3400-106d-11eb-8879-4bbf90215f7d.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser We can add translations to those two labels, but below translation text is too long for that label.

"mainnet": "Rede principal",
"testnet": "Rede teste"

**Comment by bitcoinuser** [comment]
> @bitcoinuser We can add translations to those two labels, but below translation text is too long for that label.
> 
> "mainnet": "Rede principal",
> "testnet": "Rede teste"

In this specific case, please translate to Principal and Teste. No need to add the word Rede in front of this.

Thanks.

**Comment by chrisli30** [comment]
@imstar15 please update the translations to below text

"mainnet": "Principal",
"testnet": "Teste"

**Comment by bitcoinuser** [comment]
Fixed.
