### ISSUE TITLE
(Back to Wallet) button goes to (Select Asset) window instead of main wallet window.

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#569]
RWallet 1.3.1 on Android

I did a transaction using RBTC and after the transaction I clicked on (Back to Wallet) button. I was redirected to Select Asset window, but I should be redirected to Rwallet main window.

When I click on Back to Wallet button I was redirected to this window:

![photo_2020-10-22_21-28-38](https://user-images.githubusercontent.com/1178856/96943129-98c6df80-14ad-11eb-82bb-347adebcbcf2.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser Sorry I don't get this issue. Did you click "Confirm" in the Sending page?

Do you get to this step?

![image](https://user-images.githubusercontent.com/2616844/97518730-1333ab80-1955-11eb-8d9b-3a58f5bb8ad5.png)

**Comment by bitcoinuser** [comment]
> Do you get to this step?

Yes, now if I click on Go to Wallet button, I'm redirected to Select asset window, instead of main wallet window.

**Comment by chrisli30** [comment]
@imstar15 do you get that scenario? I'm still confused.
