### ISSUE TITLE
RBTC payment on Sending status just disappeared 

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#570]
RWallet 1.3.1 on Android

I tried to send a payment using RBTC and the payment was on Sending status.
Obs. on How fast do you want this done, I chose Slow. 

Result: After some time the payment on sending status just disappeared.

Expected: Show the payment as confirmed or failed and show some notification too.

**Comment by bitcoinuser** [comment]
What is strange is that the transaction appeared to the person that I sent it as receiving. And for him the transaction disappeared too.
My address is: https://blockscout.com/rsk/mainnet/address/0x992230f727e8DB1B3bA71f6AFBa8be33d18Aa02b/transactions

**Comment by bitcoinuser** [comment]
And I don't know if I have the same balance as before I sent the transaction or not.

**Comment by imstar15** [comment]
What is the hash and amount of this transaction?

@bitcoinuser

**Comment by bitcoinuser** [comment]
I was able to find the hash: https://explorer.rsk.co/tx/0xab38134aef46dc1118733c994dec902dcd04454ad10e1954ba9110bfd2d9de0e

**Comment by bitcoinuser** [comment]
> Is it this transaction?
> https://blockscout.com/rsk/mainnet/tx/0xbf63a4593af5aa6edb6fd705bed2642d7ad213ff38711051321f9ecce802c392/internal-transactions

No, this is my address

**Comment by bitcoinuser** [comment]
The transaction was 0.00022. I was able to print the screen before disappeared:

![photo_2020-10-23_09-10-46](https://user-images.githubusercontent.com/1178856/97002107-df4d2600-150f-11eb-800a-ab21df37837c.jpg)

**Comment by bitcoinuser** [comment]
@chrisli30 When sending the balance should change or just change when it's sent?

**Comment by chrisli30** [comment]
> I was able to find the hash: https://explorer.rsk.co/tx/0xab38134aef46dc1118733c994dec902dcd04454ad10e1954ba9110bfd2d9de0e

For BTC, the transfer amount is deducted from the balance when a transaction is sending.

For RBTC, the amount is not deducted. That's due to the difference of the chain implementation.

You transaction has disappeared from [the explorer](https://explorer.rsk.co/tx/0xab38134aef46dc1118733c994dec902dcd04454ad10e1954ba9110bfd2d9de0e) and rwallet backend. We have seen the case of transactions missing from the explorer before. When that happens it has never happened on chain, and user won't be able to see the transaction in history.

**Comment by chrisli30** [comment]
In the new version we will add a logic to record your send transaction even it's not recorded/reverted by the blockchain. Although there's no way to confirm that transaction if it's reverted, we will still be able to see that you once tried to send it.

Closing this issue for now. When it happens again we will be able to see it in rwallet v1.3.4 and onward
