### ISSUE TITLE
Landscape not supported

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#576]
**Describe the bug** (required)
Landscape is not supported. You can lock screen flip when landscape position if not supported. 

**App & Device** (required)
 - Wallet App version: latest
 - Device: iPhone XR
 - OS version: latest

**To Reproduce**
1. Go to home
2. Flip device

**Screenshots** (required for high priority)

![A5739D6E-A95B-41DF-96CB-3064F9CB3189](https://user-images.githubusercontent.com/36084092/97397384-e08fa180-18c7-11eb-9e84-a4f0e5caa59f.png)
![1E0D02D6-1534-41F1-B69B-E0F355F0AC9F](https://user-images.githubusercontent.com/36084092/97397390-e2f1fb80-18c7-11eb-964b-62fdaf3ca180.png)
![3B48F041-6C8D-4FA2-B05E-FAA09E2660BD](https://user-images.githubusercontent.com/36084092/97397398-e4bbbf00-18c7-11eb-9a2e-dfa1261a38d9.png)

**Expected behavior**
Landscape disabled

**Comment by chrisli30** [comment]
@ilanolkies This is a great report! We shoulda had landscape disabled. 👍 

@imstar15 Could you arrange to get this fixed?
