### ISSUE TITLE
rskswap.com Wallet Connect can't connect using RWallet

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#578]
RWallet 1.3.2

I tried to connect on rskswap.com using Wallet Connect but after I read the qrcode appear this message on rskswap: error connecting, try again.

On Defiant app the Wallet Connect works ok on rskswap.com

**Comment by chrisli30** [comment]
@bitcoinuser I didn't see the Defiant on iOS. Could you send a link to it so we can test?

rskswap.com doesn't support testnet. Are you connecting to mainnet?

With my rwallet, it was able to connect but not able to retrieve account balance. That's a known bug for the site.

**Comment by bitcoinuser** [comment]
> I didn't see the Defiant on iOS. Could you send a link to it so we can test?

https://defiantapp.tech/

> rskswap.com doesn't support testnet. Are you connecting to mainnet?

Yes, I tested with mainnet

> With my rwallet, it was able to connect but not able to retrieve account balance. That's a known bug for the site.

I think the bug is with RWallet as Defiant wallet works ok.

**Comment by chrisli30** [comment]
@bitcoinuser I tested rskswap with Defiant and it works with below screenshot. Is their wallet open-source? Is there any way we can check out how they made it work? We've been trying different things to make it work but haven't succeeded.

![image](https://user-images.githubusercontent.com/2616844/97488015-ed89b080-191a-11eb-96bd-3bd6368db2c4.png)

**Comment by AmazingBeerBelly** [comment]
Fixed PR #594
