### ISSUE TITLE
RWallet on iOS show the popup to update but no option to update is available on Applestore

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#595]
RWallet on iOS show the popup to update but no option to update is available on Applestore

Two people reported this problem. They say the version installed is 1.3.2

**Comment by imstar15** [comment]
Yes, 1.3.3 has not been released yet.
I have adjusted the server configuration again. Please restart the App.

@bitcoinuser

**Comment by bitcoinuser** [comment]
People say it's working now.
