### ISSUE TITLE
Transaction on test Sovryn always fail when using RWallet but the same transaction works on Defiant app

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#596]
RWallet 1.3.3 on Android

Transaction on Sovryn always fail when using RWallet but the same transaction works on Defiant app

Try to trade short on https://test.sovryn.app/ with 50 DoC using RWallet connected using WalletConnect

Result: Fail.

Try the same operation using Defiant app.

Result: Transaction successful

**Comment by chrisli30** [comment]
Okay, noted. We will work on the fix and test both Testnet and Mainnet.
