### ISSUE TITLE
Internal server error when trying to send tbtc

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#597]
RWallet 1.3.3 on Android

Internal server error when trying to send tbtc.

![photo_2020-11-04_21-10-17](https://user-images.githubusercontent.com/1178856/98181524-4391c180-1ee2-11eb-8f2a-9f28999d75f0.jpg)

**Comment by chrisli30** [comment]
@bitcoinuser We will take a look at this error. What's your own BTC sender address?

**Comment by bitcoinuser** [comment]
> @bitcoinuser We will take a look at this error. What's your own BTC sender address?

tb1qr4ael6js5rpp5eqe5f37almyrefaajcn8q08zt

**Comment by imstar15** [comment]
It has been resolved, please try again.

@bitcoinuser

**Comment by bitcoinuser** [comment]
Fixed.
