### ISSUE TITLE
Clicking on Android back button on a Dapp webpage should show a popup to confirm to exit the page

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#600]
RWallet 1.3.3 on Android

Clicking on Android back button on a Dapp webpage should show a popup to confirm to exit the page. 

Why: Many times I click on Android back button thinking that I will go back do previous webpage but instead the webpage is closed.

**Comment by chrisli30** [comment]
@AmazingBeerBelly is there a way to Go Back in the web browser, instead of exit the web browser?
