### ISSUE TITLE
Swapping from DoC to BTC timed out

### ISSUE THREAD

**Issue by juanlentino** [rsksmart/rwallet#602]
I sent some funds to my wallet and swapped it to DoC. When I try to swap it again to BTC, it gives me a time out.

**App & Device** (required)
 - Wallet App version: 1.1.3
 - Device: iPhone11 Pro Max
 - OS version: iOS 14.2
 
**Screenshots** (required for high priority)
![IMG_F58C15ECABCE-1](https://user-images.githubusercontent.com/74268474/98728484-53912180-2378-11eb-99d4-c1ec372767d6.jpeg)

**Comment by chrisli30** [comment]
Hi @juanlentino, the timeout might caused by the swap service. I have two questions below.
1. Is your wallet app version 1.3.3 or 1.1.3? 
1. Did you click on the Retry and try it again?

**Comment by juanlentino** [comment]
> Hi @juanlentino, the timeout might caused by the swap service. I have two questions below.
> 
> 1. Is your wallet app version 1.3.3 or 1.1.3?
> 2. Did you click on the Retry and try it again?

1. Sorry, it's 1.3.3. My bad.
2. I did, but I got the same time out.

**Comment by chrisli30** [comment]
> > Hi @juanlentino, the timeout might caused by the swap service. I have two questions below.
> > 
> > 1. Is your wallet app version 1.3.3 or 1.1.3?
> > 2. Did you click on the Retry and try it again?
> 
> 1. Sorry, it's 1.3.3. My bad.
> 2. I did, but I got the same time out.

Hi @juanlentino , we checked the logs. The request was timed out when we forwarded it to the third-party service, Coinswitch . Their service is restored and we verified that. Please try convert again.

Sorry about the inconvenience.

**Comment by juanlentino** [comment]
@chrisli30, I still have the same problem. I just tried and re-tried, but no luck.

**Comment by tinyyxx** [comment]
> @chrisli30, I still have the same problem. I just tried and re-tried, but no luck.

Hi, @juanlentino . What is your DOC address when using coinSwitch?

**Comment by tinyyxx** [comment]
Hi, @juanlentino . I have update server and add some extra logs output to track your issue. Please use coinSwitch again, and tell me what is DoC address and BTC address when you use coinSwitch

**Comment by juanlentino** [comment]
@tinyyxx, I think the DoC address is 0x08Fa1E765E44c77E572AFb1a68542fe3C19A6989 and the BTC one is bc1q0c59n90nazcrs0euwz0zfe7aajkemw4mkv2nle.
Thanks for the help to you and @chrisli30.

**Comment by tinyyxx** [comment]
@juanlentino Hi, it is a little hard to find you problem, I try DoC- > BTC successfully. So can you try create a another wallet and transfer your DOC to that wallet, then switch to btc ?

**Comment by juanlentino** [comment]
@tinyyxx, I tried what you said here:
> By the way, it is a little hard to figure out you problem, your log is normal, and I try DoC- > BTC successfully.
> So if your are hurry to use that 340 DOC , I think you can try create a another wallet and transfer your DOC to that wallet, then switch to btc ?
But it didn't work.

So I guess I'll go with the MoC DApp solution and see if that works. 
Thanks for everything.

**Comment by tinyyxx** [comment]
@juanlentino Hi, I noticed that your DoC is still not spent, anything I can help you ?
And what happen when you transfer your DoC as you said above it didn't work.

**Comment by juanlentino** [comment]
@tinyyxx, I couldn't do anything that you and @chrisli30 recommended.
I guess I'll keep those DoC there until there's a fix if there are more issues like mine.

**Comment by tinyyxx** [comment]
> @tinyyxx, I couldn't do anything that you and @chrisli30 recommended.
> I guess I'll keep those DoC there until there's a fix if there are more issues like mine.

@juanlentino Why couldn't do anything, can you give me more detail about it? I think the normal transfer function should be ok. If not work, please upload some screenshot.

I have another suggestion, you can try to download rwallet in another device, and import your wallet with your mnemonic, use that device to transfer or coinSwitch?

**Comment by juanlentino** [comment]
Well, everything I do in the wallet get the same time out thing.
Bare with me that I’m not a developer, just an user that wanted to use the
wallet.
*Juan Lentino*
juan.lentino@gmail.com

**Comment by juanlentino** [comment]
Well, everything I do in the wallet gets the same time out thing.
Bare with me that I’m not a developer, just a user that wanted to use the
wallet.

**Comment by chrisli30** [comment]
> Bare with me that I’m not a developer, just a user that wanted to use the

Understood, sorry about the inconvenience. I think you hit an edge case of the app and we are not able to reproduce the bug on our devices. We've added more logging(developer output) to help debug your case and will publish a new version 1.3.4 next week. Once published, I'll ask you to upgrade the app and try again.

Again, sorry about the timeout experience.

**Comment by juanlentino** [comment]
> > Bare with me that I’m not a developer, just a user that wanted to use the
> 
> Understood, sorry about the inconvenience. I think you hit an edge case of the app and we are not able to reproduce the bug on our devices. We've added more logging(developer output) to help debug your case and will publish a new version 1.3.4 next week. Once published, I'll ask you to upgrade the app and try again.
> 
> Again, sorry about the timeout experience.

No problem, @chrisli30. I've tried everything you and @tinyyxx told me. I'll leave the coins there until you release that update. I hope it fixes it, so I can recover them.

**Comment by chrisli30** [comment]
Yeah, don't worry. You funds are safe : )

 Remember to backup the master seed in the last tab, Me. Click on the wallet from Me page and you will see a Back up button at the bottom.

**Comment by juanlentino** [comment]
> Yeah, don't worry. You funds are safe : )
> 
> 
> 
>  Remember to backup the master seed in the last tab, Me. Click on the wallet from Me page and you will see a Back up button at the bottom.

@chrisli30 Long time, no talk. I still have the same problem.
I’m going to try to delete the app and restore the wallet.
Perhaps that will work; what do you think?

**Comment by chrisli30** [comment]
> > Yeah, don't worry. You funds are safe : )
> > Remember to backup the master seed in the last tab, Me. Click on the wallet from Me page and you will see a Back up button at the bottom.
> 
> @chrisli30 Long time, no talk. I still have the same problem.
> I’m going to try to delete the app and restore the wallet.
> Perhaps that will work; what do you think?

Yeah, please try that. As long as you have the 12-word you funds are safe in the wallet.

My team is moved off of the rwallet project so can't help with the trouble shooting any more : (

**Comment by juanlentino** [comment]
So, who can help me now?
I’ve deleted the wallet; I imported it back, and it didn't work. 
Then I deleted the wallet and the app from my phone; it didn't work either. 

What should I do to swap it to BTC?

**Comment by bitcoinuser** [comment]
> So, who can help me now?
> I’ve deleted the wallet; I imported it back, and it didn't work.
> Then I deleted the wallet and the app from my phone; it didn't work either.
> 
> What should I do to swap it to BTC?

This RSK wallet is more stable and you can import the seed their: https://play.google.com/store/apps/details?id=ar.com.andinasmart.defiant&hl=en_US&gl=US

**Comment by juanlentino** [comment]
> > So, who can help me now?
> 
> > I’ve deleted the wallet; I imported it back, and it didn't work.
> 
> > Then I deleted the wallet and the app from my phone; it didn't work either.
> 
> > 
> 
> > What should I do to swap it to BTC?
> 
> 
> 
> This RSK wallet is more stable and you can import the seed their: https://play.google.com/store/apps/details?id=ar.com.andinasmart.defiant&hl=en_US&gl=US
> 
> 
> 
> Site: https://defiantapp.tech/home/

Thanks, but I have iOS, and that app is in beta.

**Comment by patogallaiovlabs** [comment]
Hi @juanlentino !
Did you manage to swap? If not please check our #support channel in slack: open-rsk-dev.slack.com
We are no longer supporting this functionality in rWallet for now, and will be disabled in the next release.
Thank you for your time and patience.
