### ISSUE TITLE
Internal server error - When trying to Swap BTC to RBTC

### ISSUE THREAD

**Issue by Tenguashi** [rsksmart/rwallet#633]
Have BTC in wallet. Trying to swap BTC to RBTC, but when I enter the Swap screen and click on BTC I get the "Internal server error - Please contact customer support" error. It has cancel and retry as options. I have tried multiple times over past few days and get same error. I even loaded RWallet on wife's iPhone thinking it may be my phone, but still get the same error

**App & Device** (required)
 - Wallet App version: v1.3.3
 - Device: Galaxy Note 8 & IPhone 7
 - OS version: REV1.1
 
**To Reproduce**

**Screenshots** (required for high priority)

**Expected behavior**

**Additional context**
- (optional: include links to other issues, PRs, tickets, etc)

**Comment by beepboop1234** [comment]
Same error here on a OnePlus 7 Pro. Also app v1.3.3. Android Oxygen OS v10.

**Comment by therafinest** [comment]
I have the same issue on iOS 13.6.1
![IMG_5049](https://user-images.githubusercontent.com/79519994/108847134-3b67aa00-75d7-11eb-8e08-0a601622e76d.PNG)
