### ISSUE TITLE
Update android app on google-play (it's old version 1.3.3 with missing tag)

### ISSUE THREAD

**Issue by emanuelb** [rsksmart/rwallet#662]
Visiting:
https://play.google.com/store/apps/details?id=com.rsk.rwallet.reactnative
Shows: "Current Version 1.3.3" "Updated October 29, 2020"

While the latest tag is `v1.4.1`: https://github.com/rsksmart/rwallet/releases/tag/v1.4.1 which also contain apk to download.
There is no tag for version 1.3.3 on google-play, please tag the relevant commit for this version as well, and update the version on google-play to latest version/tag.

**Comment by patogallaiovlabs** [comment]
Hi @emanuelb,
We are currently working in the review of the App for Android, is almost ready. In the meantime I removed the apk from the release, until we get the approval.
Thanks for opening the issue, I will close it once we get the update.

**Comment by emanuelb** [comment]
No need to remove the APK from releases! it's very useful to have .apk + .ipa files in github releases, can be used directly and doing so avoiding google/apple stores, such as phones without play-store, and for other purposes such as testing, etc..

**Comment by patogallaiovlabs** [comment]
APK was removed due to inconsistency in the release. Anyway new APK and version have been release. So closing issue, thanks for reporting.

**Comment by emanuelb** [comment]
Did you change appid in the releases on purpose? it's `com.rsk.rwallet.v2` now:
https://play.google.com/store/apps/details?id=com.rsk.rwallet.v2
old link for appid `com.rsk.rwallet.reactnative` return not found now:
https://play.google.com/store/apps/details?id=com.rsk.rwallet.reactnative
