### ISSUE TITLE
Some icons are strange on version 1.4.2

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#667]
Some icons are strange on version 1.4.2

Android version from: https://github.com/rsksmart/rwallet/releases/tag/v1.4.2

See:

![photo_2021-04-23_11-31-38](https://user-images.githubusercontent.com/1178856/115886844-b73f7080-a427-11eb-9b63-b71d495ab3dc.jpg)

![photo_2021-04-23_11-27-50](https://user-images.githubusercontent.com/1178856/115886855-bc042480-a427-11eb-9aea-25d912267728.jpg)

![photo_2021-04-23_11-28-01](https://user-images.githubusercontent.com/1178856/115886870-c0304200-a427-11eb-9451-e379f8069d9e.jpg)

**Comment by bitcoinuser** [comment]
Please disable dark theme on Rwallet.

**Comment by patogallaiovlabs** [comment]
Fixed in v2.0.1
