### ISSUE TITLE
No License provided?

### ISSUE THREAD

**Issue by mirkoAlic** [rsksmart/rwallet#81]
Hey, maybe i missing something, but i can't find the licence for this code..Could you clarify the situation?

Thanks in advance.

**Comment by mirkoAlic** [comment]
(just in case: https://choosealicense.com/no-permission/)

**Comment by chrisli30** [comment]
@mirkoAlic thanks for your feedback. Going through history I found that the license file was removed by mistake... We are adding them back. I will ping you back here once added.

**Comment by mirkoAlic** [comment]
solved =)

**Comment by chrisli30** [comment]
@mirkoAlic Thank you man for pointing it out! 💯
