### ISSUE TITLE
Feature request: Support for Native Segwit/Bech32

### ISSUE THREAD

**Issue by grunch** [rsksmart/rwallet#85]
Please add segwit native support, for many bitcoiners is very important to use bech32 addresses and avoid to pay more fees using the obsolete legacy addresses.

**Comment by franamati** [comment]
Pls this is practically a must in a Bitcoin sidechain wallet, it won't be well received in the Bitcoin community without it. Thanks!

**Comment by chrisli30** [comment]
Thanks for reporting @grunch and @franamati !

The segwit support is in the planning pipeline. We will have a discussion to see if we need to bump it up.

**Comment by chrisli30** [comment]
Two places to ask user to choose BTC wallet:
1. During creation
1. During Bitcoin Token enable (if not enabled during creation)

**Comment by franamati** [comment]
It's 2020, why asking? :)

It's simpler.

Trust Wallet, Coinbase Wallet, Exodus, Crypto.com Wallet, Defiant, HODL Wallet, no longer ask and don't have a way to create legacy addresses.

And many wallets still supporting legacy addresses are neither asking, they only have the option for people looking for those (Muun, Exodus, Coinomi, Electrum).

**Comment by chrisli30** [comment]
@imstar15 , Please check above devices for a good reference of how Segwit is shown on other wallets ☝️  ☝️ 

Thanks @franamati

**Comment by imstar15** [comment]
legacy: m/44'/0'/0'/0/0
segwit: m/84'/0'/0'/0/0
