### ISSUE TITLE
Can't send non-integer amounts

### ISSUE THREAD

**Issue by franamati** [rsksmart/rwallet#93]
On iOS amount field only allows a dot (".") for decimal amounts, but the keyword shown is only numbers and a comma (","). If I use the comma (the dot is not in the keyboard) it says "Amount is not valid".

A workaround I found is to use "send all", that will type a dot if my full amount is not an integer, and then I can change the numbers before an after that dot.

My iOS language set is "English" and my region set is "Argentina".

Screenshot:
![rWallet amounts](https://user-images.githubusercontent.com/8605599/80316291-60329b80-87d3-11ea-823b-09e155e31ca9.png)

**Comment by chrisli30** [comment]
Thanks @franamati. Your keyboard is launched by your iOS system. The app doesn't have a custom keyboard implemented.

What OS version is your iOS device? Can you switch to a different keyboard?

**Comment by chrisli30** [comment]
@imstar15 we need to research what other app do allow "," in Argentinian amount input.

**Comment by franamati** [comment]
Sorry for not answering before. Confirmed fixed.

**Comment by chrisli30** [comment]
@franamati Glad we were able to help. Thanks! Please let us know if you have any other questions.
